// Package stressy provides CPU stress testing functionality through controlled
// worker goroutines that perform intensive cryptographic operations.
package stressy

import (
	"context"
	"errors"
	"fmt"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// hashCost is the bcrypt cost every worker hashes at.
//
// bcrypt doubles its work per increment, so the cost is not a load setting —
// it is how long one uninterruptible GenerateFromPassword call runs, and
// therefore how long a worker takes to notice cancellation, since it can only
// check between calls. Cost 12 measures ~0.18s per hash on an M-series core.
// bcrypt.MaxCost, which this used to use, measures ~26 hours by the same
// doubling: it pegged a core no harder and made the cancellation check below
// unreachable (#15).
const hashCost = 12

// Stressy represents a CPU stress testing instance.
// It manages multiple worker goroutines that perform CPU-intensive operations
// and handles graceful shutdown through signals or timeouts.
type Stressy struct {
	workers int           // number of parallel worker goroutines
	timeout time.Duration // how long to run (0 for indefinite)
}

// Cfg holds the configuration parameters for creating a new Stressy instance.
type Cfg struct {
	Workers int           // number of parallel worker goroutines
	Timeout time.Duration // how long to run (0 for indefinite)
}

// New creates and returns a new Stressy instance with the given configuration.
// The instance is ready to start but not yet running.
func New(c Cfg) *Stressy {
	return &Stressy{
		workers: c.Workers,
		timeout: c.Timeout,
	}
}

// Run starts the CPU stress test with the configured number of workers.
// It handles:
//   - Configuration validation
//   - Worker goroutine management
//   - Timer management (if timeout > 0)
//   - Signal handling (SIGINT, SIGTERM)
//   - Graceful shutdown
//
// The test runs until either:
//   - The timeout duration is reached (if configured)
//   - An interrupt signal is received
//
// Run then waits for every worker to finish the hash it is on, so it returns
// up to one hash after the shutdown was triggered. Returns an error if the
// configuration is invalid.
func (s *Stressy) Run() error {
	if err := s.validateConfig(); err != nil {
		return err
	}

	fmt.Println(s.startupMessage())
	fmt.Println("Use --help for additional information")

	// One context carries both shutdown triggers, which is what makes them
	// safe to race: a context cancels once no matter how many sources fire,
	// where the two hand-rolled `close(s.done)` calls this replaces could both
	// run and panic the process (#14). Installed before the workers start, so
	// a signal arriving immediately is not missed.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	if s.timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, s.timeout)
		defer cancel()
	}

	var wg sync.WaitGroup
	wg.Add(s.workers)
	for range s.workers {
		go func() {
			defer wg.Done()
			s.stressTestCPU(ctx)
		}()
	}

	<-ctx.Done()

	// Only the timeout produces DeadlineExceeded; a signal cancels the parent,
	// which surfaces here as Canceled.
	if errors.Is(ctx.Err(), context.DeadlineExceeded) {
		fmt.Println("Timer expired, shutting down...")
	} else {
		fmt.Println("Received signal, shutting down...")
	}

	wg.Wait()

	return nil
}

// startupMessage is the line Run prints before the workers start: how many of
// them, and for how long. It is the first thing every user of this tool sees,
// and it used to open with "1 workers" on the default run (#17c).
//
// Built as a string rather than printed in place so that it is testable
// without capturing os.Stdout.
func (s *Stressy) startupMessage() string {
	workers := "workers"
	if s.workers == 1 {
		workers = "worker"
	}

	// The timeout is a time.Duration and formats itself — "30s", "5m0s" — so
	// the other half of #17c, "1 seconds", went with the duration flag in #26.
	duration := "indefinitely"
	if s.timeout > 0 {
		duration = "for " + s.timeout.String()
	}

	return fmt.Sprintf("Starting CPU stress test with %d %s %s", s.workers, workers, duration)
}

// validateConfig checks if the Stressy instance's configuration is valid.
// Returns an error if:
//   - workers is less than 1
//   - timeout is negative
func (s *Stressy) validateConfig() error {
	if s.workers < 1 {
		return fmt.Errorf("workers must be 1 or greater")
	}

	if s.timeout < 0 {
		return fmt.Errorf("timeout must be 0 (indefinite) or greater")
	}

	return nil
}

// stressTestCPU performs CPU-intensive operations in a loop.
// It runs in its own goroutine and continues until ctx is cancelled. The CPU
// load is generated by repeatedly computing bcrypt hashes at hashCost, which
// is where the whole of the load lives — bcrypt salts every call itself, so
// nothing outside the hash has to vary for the work to be real, and a worker
// returns within one hash of ctx being done.
func (s *Stressy) stressTestCPU(ctx context.Context) {
	// Hoisted: formatting a timestamp per iteration was never the load this
	// tool exists to generate, and a constant keeps the input well inside
	// bcrypt's 72-byte limit rather than merely under it by accident.
	password := []byte("stressy")

	for {
		select {
		case <-ctx.Done():
			return
		default:
			// Unreachable in practice: the cost is a valid constant and the
			// password is seven bytes, which leaves salt generation as the
			// only error source, and crypto/rand no longer reports failure.
			if _, err := bcrypt.GenerateFromPassword(password, hashCost); err != nil {
				panic(err)
			}
		}
	}
}
